name: Run Tests in MATLAB Project
on: [push]
jobs:
  my-job:
    name: Run MATLAB Tests
    runs-on: [self-hosted, Windows, x64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4        
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
          test-results-junit: test-results/results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: matlab-test-results
          path: test-results/results.xml
